version: "3.0"

services:
  api:
    build: .
    image: api
    depends_on:
        - 'attack'
        - 'planet'
        - 'jwks'
        - 'nats-server'
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    ports:
      - "3000:3000"

  jwks:
    build: .
    image: jwks
    depends_on:
        - 'nats-server'
    env_file: docker-compose.env
    environment:
      SERVICES: jwks

  attack:
    build: .
    image: attack
    depends_on:
        - 'nats-server'
    env_file: docker-compose.env
    environment:
      SERVICES: attack

  planet:
    build: .
    image: planet
    depends_on:
        - 'nats-server'
    env_file: docker-compose.env
    environment:
      SERVICES: planet

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
